#ifndef ATHLETICSBRANCH_H_INCLUDED
#define ATHLETICSBRANCH_H_INCLUDED

enum AthleticsBranch {
    RUNNING, THROWING, JUMPING, WALKING, HEPTATHLON, DECATHLON
};

#endif // ATHLETICSBRANCH_H_INCLUDED
